version: '2'

services:
    web:
        image: nginx:1.11.5-alpine
        restart: always
        ports:
         - "1618:80"
        volumes:
         - ./dist:/usr/share/nginx/html
        environment:
         - NGINX_PORT=80